### ISSUE TITLE
`UnsafeHelper.AsSpan<T>(Array)` 实现错误

### ISSUE THREAD

**Issue by Executor-Cheng** [ilyfairy/UnsafeHelper#9]
https://github.com/ilyfairy/UnsafeHelper/blob/dcc97569003da0d9e0c097c035a5226948299984/UnsafeHelper/UnsafeHelper.cs#L380-L389

1. L383 判空太迟了, 如果传入的 `array` 是 null, 那么在 L382 处就会抛 `NullReferenceException`
2. 由于返回的是一个 `Span<T>`, 需要考虑 `T` 在内存中所占大小, 以此调整返回的 `Span<T>` 长度。并且需要考虑传入数组与传出的 `Span<T>` 数据大小有无法整除的情况, 比如 `byte[3, 3]` -> `Span<int>`, `byte[3,3]` 数据区域是9字节, `Span<int>` 的长度至多为2
    > 参考 [MemoryMarshal.Cast<TFrom, TTo>(Span<TFrom>)](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/MemoryMarshal.cs,75c6da1c26bac793)
3. 从 .NET 6.0 起, 可以考虑通过 `MemoryMarshal.GetArrayDataReference(Array)` 获取数据区域的引用, .NET 5.0 还是需要自己搓一个的, 具体得用到 `MethodTable` 这个结构来计算偏移, 以及传入数组数据区域的大小, 大概很快我会发一个PR加上对 `MethodTable` 的支持

**Comment by ilyfairy** [comment]
MemoryMarshal.GetArrayDataReference的话, 它好像只能传入一维数组

**Comment by Executor-Cheng** [comment]
> MemoryMarshal.GetArrayDataReference的话, 它好像只能传入一维数组

n维都可以, 内部实现保证了能够获取到第一个元素的引用
```csharp
nuint[,] twoRank = new nuint[2, 2] { { 1, 2 }, { 3, 4 } };
nuint[,,] threeRank = new nuint[3, 3, 3];
nuint t = 0;
for (int i = 0; i < 3; i++)
{
	for (int j = 0; j < 3; j++)
	{
		for (int k = 0; k < 3; k++)
		{
			threeRank[i, j, k] = ++t;
		}
	}
}
ref nuint twoRankRef = ref Unsafe.As<byte, nuint>(ref MemoryMarshal.GetArrayDataReference(twoRank));
ref nuint threeRankRef = ref Unsafe.As<byte, nuint>(ref MemoryMarshal.GetArrayDataReference(threeRank));
```
你可以验证一下 `twoRankRef` 和 `threeRankRef` 解引用后是不是均为1

**Comment by ilyfairy** [comment]
原来有重载, 我没看见, 我改改

**Comment by Executor-Cheng** [comment]
> 原来有重载, 我没看见, 我改改

是滴, 但这个重载仅限 .NET 6.0+, 5.0要自己搓一个

**Comment by ilyfairy** [comment]
修复了qwq

**Comment by ilyfairy** [comment]
如果要自己实现这个MethodTable的话

对于定义, 用哪个比较好
- ref struct MethodTable
- struct MethodTable

对于其他方法的返回或者引用, 用什么比较好
- ref MethodTable
- MethodTable*

**Comment by Executor-Cheng** [comment]
没改对哦, 你没考虑x86的情况

https://github.com/ilyfairy/UnsafeHelper/blob/6cc8e4f06d0bbe78e75157d0d443e68290caad47/UnsafeHelper/UnsafeHelper.cs#L415
这句应为 `var p = (byte*)addr + sizeof(nuint) + offset;`
引入 `MethodTable` 后应该能用更简单的方式计算以上, 然后就能产出更少的汇编
我是这么玩儿的, 因为涉及到计算传入数组数据区域的长度, 所以索性不用 `MemoryMarshal.GetArrayDataReference(Array)` 了, 直接自己造
```csharp
if (array == null) throw new ArgumentNullException(nameof(array));
ref MethodTable mt = ref GetMethodTableReference(array);
ref nuint arrayRawDataRef = ref GetRawDataReference(array);
nuint rawSize = mt.BaseSize - (uint)(2 * sizeof(nuint));
nuint arrayDataSize = Unsafe.As<nuint, uint>(ref arrayRawDataRef) * (nuint)mt.ComponentSize;
ref T dataRef = ref Unsafe.As<nuint, T>(ref Unsafe.AddByteOffset(ref arrayRawDataRef, (nint)rawSize));
return MemoryMarshal.CreateSpan(ref dataRef, (int)(arrayDataSize / (uint)sizeof(T)));
```

`MethodTable` 在堆上, 所以应当用 `struct`, 我是这么定义的
```csharp
[StructLayout(LayoutKind.Explicit)]
public unsafe struct MethodTable
{
	private const int PtrSize =
#if TARGET_64BIT
		8
#else
		4
#endif
		;

	[FieldOffset(0)]
	public ushort ComponentSize;

	[FieldOffset(0)]
	public uint Flags;

	[FieldOffset(4)]
	public uint BaseSize;

	// 0x8: m_wFlags2

	// 0xA: m_wToken

	[FieldOffset(0xC)]
	public ushort VirtualsCount;

	[FieldOffset(0xE)]
	public ushort InterfaceCount;

	[FieldOffset(0x10)]
	public MethodTable* ParentMethodTable;

	[FieldOffset(0x10 + 4 * PtrSize)]
	public void* ElementType;

	[FieldOffset(0x10 + 5 * PtrSize)]
	public MethodTable** InterfaceMap;
}
```

昨天晚上我改了不少东西, 只是还没改完, 改到这个 `AsSpan<T>` 的时候发现了点不对, 所以就先问问看你有啥意见

**Comment by ilyfairy** [comment]
那到时候定义一个MethodTable.
那个地址的话, 我应该是没写错,我获取的是越过了`MethodTable*`区域的地址
`System.Runtime.CompilerServices.RawArrayData`应该是数组数据的定义
Array: `MethodTable*, Length, Padding, Data`
+8是加的(`Length+Padding`)

**Comment by Executor-Cheng** [comment]
> 那到时候定义一个MethodTable. 那个地址的话, 我应该是没写错,我获取的是越过了`MethodTable*`区域的地址 `System.Runtime.CompilerServices.RawArrayData`应该是数组数据的定义 Array: `MethodTable*, Length, Padding, Data` +8是加的(`Length+Padding`)

[RuntimeHelpers.RawArrayData](https://source.dot.net/#System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs,9cc1d4c1775aedc3)
L432-L434 仅在x64下才会被编译, 所以在x86下Padding就没有啦

**Comment by ilyfairy** [comment]
> > 那到时候定义一个MethodTable. 那个地址的话, 我应该是没写错,我获取的是越过了`MethodTable*`区域的地址 `System.Runtime.CompilerServices.RawArrayData`应该是数组数据的定义 Array: `MethodTable*, Length, Padding, Data` +8是加的(`Length+Padding`)
> 
> [RuntimeHelpers.RawArrayData](https://source.dot.net/#System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs,9cc1d4c1775aedc3) L432-L434 仅在x64下才会被编译, 所以在x86下Padding就没有啦

原来是这样, 我经常看dnspy, 估计很多东西都弄错了

**Comment by Executor-Cheng** [comment]
我给的 `MethodTable` 倒数三个成员好像偏移不准确, 先找找看怎么回事我再发PR吧

**Comment by Executor-Cheng** [comment]
搞明白了, 这个 `TARGET_64BIT` 是微软自己搞的宏, 在其它项目里边这个宏永远未定义, 所以我写在 `MethodTable` 上边的偏移炸了, 得自己在csproj里边加点东西来定义它。`MethodTable` 本身是没问题的
```xml
<PropertyGroup Condition="'$(PlatformTarget)' == 'AnyCPU'">
  <Prefer32Bit>false</Prefer32Bit>
  <DefineConstants>TARGET_64BIT;$(DefineConstants)</DefineConstants>
</PropertyGroup>
<PropertyGroup Condition="'$(PlatformTarget)' == 'x86'">
  <DefineConstants>TARGET_32BIT;$(DefineConstants)</DefineConstants>
</PropertyGroup>
<PropertyGroup Condition="'$(PlatformTarget)' == 'x64'">
  <DefineConstants>TARGET_64BIT;$(DefineConstants)</DefineConstants>
</PropertyGroup>
```

**Comment by ilyfairy** [comment]
等你发Pull requests(

**Comment by Executor-Cheng** [comment]
今天上班摸鱼的时候我瞧了瞧其他人写的有关 [MethodTable](https://github.com/HexJacaranda/BlogOfHexJacaranda/blob/master/%E7%AB%A0%E8%8A%821-1%20ObjectHeader%E8%A7%A3%E6%9E%90.md) 还有 [ObjectHeader](https://github.com/HexJacaranda/BlogOfHexJacaranda/blob/master/%E7%AB%A0%E8%8A%821-1%20ObjectHeader%E8%A7%A3%E6%9E%90.md) 的博客后, 我觉得还有许多值得商榷的地方……感觉一下子说不完
比如说要不要完全支持 `MethodTable` ?
要不要支持 `ObjectHeader` 还有底下的 `SyncBlockValue` ?
要不要添加有关size方法的nuint重载?
嘛, 确实是一下子说不完了

**Comment by ilyfairy** [comment]
都可以加qwq, 等慢慢写, 不着急
我也去看看那些文章, 现在不怎么了解
